# Generated by Django 3.0.2 on 2020-09-29 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200928_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
